[package]
name = "{{ cookiecutter.package_name }}"
version = "0.1.0"
edition = "2021"

[lib]
name = "_{{ cookiecutter.package_name }}"
path = "src/rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module"] }

[profile.release]
incremental = true
